Add Windows Documentation
clearpath-docs/jackal-sphinx-tutorials pull request #1
Opened 2020-04-02 16:09 UTC by ooeygui

2020-04-02 16:11 UTC, ooeygui commented
@dniewinski Let me know if you need any changes. I tried to minimize 'Microsoft messaging'. I wanted to minimize support burden by driving to our support channels; let me know if you'd like that messaging tweaked.

2020-04-03 18:40 UTC, dniewinski requested changes

2020-04-03 18:40 UTC, dniewinski commented on doc/winstartup.rst
> +    schtasks /Create /RU <User> /RP <password> /SC ONLOGON /TN ROS /TR "c:\catkin_ws\start_ros.bat"
You'll need an extra blank line under the code declaration

2020-04-03 18:40 UTC, dniewinski commented on doc/winstartup.rst
> +    call c:\opt\ros\melodic\x64\setup.bat
You'll need an extra blank line under the code declaration

2020-04-03 19:28 UTC, ooeygui commented on doc/winstartup.rst
> +    call c:\opt\ros\melodic\x64\setup.bat
Fixed

2020-04-03 19:28 UTC, ooeygui commented on doc/winstartup.rst
> +    schtasks /Create /RU <User> /RP <password> /SC ONLOGON /TN ROS /TR "c:\catkin_ws\start_ros.bat"
Fixed

2020-04-08 16:27 UTC, civerachb-cpr requested changes

2020-04-08 16:27 UTC, civerachb-cpr commented on doc/winsetup.rst
> +    catkin_make
We're missing a cd .. command here; running catkin_make directly in the src directory fails.

2020-04-10 22:36 UTC, ooeygui commented
Going to be iterating on this. I'll issue a new PR when done.

2020-04-10 22:36 UTC, closed without merging